### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by larsbrinkhoff** [pipcet/lbForth#1]
What's the status of your JavaScript and asmjs targets?

**Comment by pipcet** [comment]
Hi Lars,
thanks for asking! To be honest, I haven't done anything lately, but I've just checked. There are three ports: JavaScript, asm.js, and an experimental...thcing where each "byte" of our machine corresponds to a JavaScript object.

IIRC, status is as follows:
The former two are working, though the JavaScript port is very slow still; the objects-as-bytes one ran fmacs at one point, but obviously isn't really compatible with actual Forth.

I'll try to have a look and see whether I can come up with something mergeable later.

**Comment by larsbrinkhoff** [comment]
Great, thanks!

**Comment by pipcet** [comment]
Status update: I've switched to using lib/meta.fth directly for the asm.js backend, which is much nicer than pretending we are C and running what's essentially a JavaScript linker on a temporary file: https://github.com/larsbrinkhoff/lbForth/compare/master...pipcet:direct-asmjs?expand=1

I'd prefer to merge the changes to lib/meta.fth to live behind switches, so they can be options for other backends. Do you agree, or do you want a separate targets/asmjs/meta.fth for now?

(The changes are:
 - custom save-target code
 - use a separate code space, so read an index rather than adding an offset for 'docol etc.

```
-: header, ( a u -- ) 2dup align here over >xt + t-word header, ;
+: header, ( a u -- ) 2dup align here t-word header, ;
```
)

**Comment by larsbrinkhoff** [comment]
Cool!

I think a common lib/meta.fth is good.  I have tried to put target-specific code in target.fth or params.fth.  But put it inside some compile-time conditionals if you like, and then it can be sorted out later.

Custom save-target code should be useful for other targets.  There should already be a way for the target to specify how to save, i.e. which binary file format to use.  But maybe you need something more.

I think you should be able to define `: >xt drop 0 ;` or something in the target, so you don't have to modify `header,`.

**Comment by larsbrinkhoff** [comment]
Typo and whitespace fixes should go in a separate commit.  But if you submit a pull request and give me write access, I can move stuff around myself.

**Comment by pipcet** [comment]
Thanks, I obviously appreciate any comments or suggestions (or improvements if you feel like it)!

I found the bug that was confusing me in src/kernel.fth, so that file is unchanged now, too.

**Comment by larsbrinkhoff** [comment]
Thanks!  I'm going to be busy over the Easter holidays, but I'll take a look soon.

**Comment by larsbrinkhoff** [comment]
The asm.js target is almost ready for merging, so I'm closing this.
